### ISSUE TITLE
How to use FieldValue 

### ISSUE THREAD

**Issue by yusuftor** [alickbass/CodableFirebase#15]
Hi, love this project. When a document is created, instead of specifying a field as a `Date` I want to set it as `FieldValue.serverTimestamp()` so that the field is the server timestamp when the doc was created. How can I use this in my model, as it's not codeable?
Thanks!

**Comment by alickbass** [comment]
Hi! Thanks for reaching out! Can you give a concrete example of how you get `FieldValue`? TBH, I have hard time finding documentation on how to use it.

**Comment by yusuftor** [comment]
Sure, you write `FieldValue.serverTimestamp()`. 
Another thing is I'm not sure how to use nested objects like if you had a name field that was split into First name and Last name like this:

```
name
    firstName : John
    lastName: Smith
```

**Comment by alickbass** [comment]
I still don't really get where `FieldValue` is coming from... How do you access it from `Firestore.firestore()`?

**Comment by alickbass** [comment]
Thanks once again for your question! I took a better look at the `FieldValue` class in the Firestore. So the thing is, that you can only use it to `setData` and `updateData` on `DocumentReference`. I think it's worth making sure that it conforms to `Encodable`. However, because when you read the data back, it becomes a `Date` instance, it's not clear how to make it `Decodable`. I will submit a PR to add support for `Encodable` for `FieldValue` and will update the README.

**Comment by alickbass** [comment]
So I have merged the PR with fix and you can check out the new README to see how it works. Don't forget to put a start for the repo 😉
